# Generated by Django 3.0.3 on 2020-02-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picker', '0014_credential_send_times_to_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('message', models.TextField(blank=True, default='')),
                ('send_time', models.DateTimeField(auto_now=True)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picker.Credential')),
            ],
            options={
                'ordering': ['send_time'],
            },
        ),
    ]
