# Generated by Django 4.0 on 2021-12-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20200406_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-send_time']},
        ),
    ]
