# Generated by Django 5.0.6 on 2024-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_audit_congregation_alter_audit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='message',
            field=models.TextField(blank=True, db_default=''),
        ),
    ]
