# Generated by Django 2.2.6 on 2019-11-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('picker', '0007_auto_20191027_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
