# Generated by Django 2.2.7 on 2019-11-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0009_auto_20191124_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['display_name', 'congregation'], 'permissions': (('access_console', 'Access to Management Console'), ('access_stopwatch', 'Access to Stopwatch'))},
        ),
    ]
