# Generated by Django 3.0 on 2019-12-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0011_auto_20191126_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='show_only_request_to_speak',
            field=models.BooleanField(default=False, verbose_name='Zeige nur Meldungen'),
        ),
    ]
