# Generated by Django 3.0.3 on 2020-02-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0012_credential_show_only_request_to_speak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['display_name', 'congregation'], 'permissions': (('access_console', 'Zugriff auf Management Console'), ('access_stopwatch', 'Zugriff auf Stoppuhr'), ('access_audit_log', 'Zugriff auf Audit-Log'))},
        ),
    ]
