# Generated by Django 3.0.3 on 2020-02-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0013_auto_20200209_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='send_times_to_stage',
            field=models.BooleanField(default=False, verbose_name='Sende Zeiten an Bühne'),
        ),
    ]
