# Generated by Django 3.0.5 on 2020-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0014_credential_send_times_to_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='extractor_url',
            field=models.CharField(blank=True, default='http://extractor:8080/', max_length=200, verbose_name='Extractor URL'),
        ),
    ]
