# Generated by Django 3.0.8 on 2020-07-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0015_auto_20200505_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='autologin',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Auto-Login ID'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='congregation',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Versammlung'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Anzeigename'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Passwort'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='touch',
            field=models.BooleanField(default=True, verbose_name='Touch erlaubt'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Username'),
        ),
    ]
