# Generated by Django 3.2.1 on 2021-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0016_auto_20200725_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['display_name', 'congregation'], 'permissions': (('access_console', 'Zugriff auf Management Console'), ('access_stopwatch', 'Zugriff auf Stoppuhr'), ('access_audit_log', 'Zugriff auf Audit-Log')), 'verbose_name': 'JWConf Verbindung', 'verbose_name_plural': 'JWConf Verbindungen'},
        ),
        migrations.AlterField(
            model_name='credential',
            name='extractor_url',
            field=models.URLField(blank=True, default='https://extractor:8080/', verbose_name='Extractor URL'),
        ),
    ]
