# Generated by Django 4.0 on 2021-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0017_auto_20210505_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='name_order',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Familienname zuerst'), (1, 'Vorname zuerst')], default=0, verbose_name='Namensreihenfolge'),
        ),
        migrations.AddField(
            model_name='credential',
            name='sort_order',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Familienname'), (1, 'Vorname')], default=0, verbose_name='Namensliste sortieren nach'),
        ),
    ]
