# Generated by Django 4.0 on 2021-12-23 10:19

import picker.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0018_credential_name_order_credential_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='extractor_url',
            field=picker.models.DockerURLField(blank=True, default='https://extractor:8080/', verbose_name='Extractor URL'),
        ),
    ]
