# Generated by Django 4.0 on 2021-12-24 10:17

import picker.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0019_alter_credential_extractor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='extractor_url',
            field=picker.models.DockerURLField(blank=True, default='https://extractor:8443/', verbose_name='Extractor URL'),
        ),
    ]
