# Generated by Django 5.0.6 on 2024-05-08 18:38

import picker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0020_alter_credential_extractor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='autologin',
            field=models.CharField(blank=True, db_default='', max_length=128, verbose_name='Auto-Login ID'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='display_name',
            field=models.CharField(blank=True, db_default='', max_length=200, verbose_name='Anzeigename'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='extractor_url',
            field=picker.models.DockerURLField(blank=True, db_default='https://extractor:8443/', verbose_name='Extractor URL'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name_order',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Familienname zuerst'), (1, 'Vorname zuerst')], db_default=0, verbose_name='Namensreihenfolge'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, db_default='', max_length=200, verbose_name='Passwort'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='send_times_to_stage',
            field=models.BooleanField(db_default=False, verbose_name='Sende Zeiten an Bühne'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='show_only_request_to_speak',
            field=models.BooleanField(db_default=False, verbose_name='Zeige nur Meldungen'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='sort_order',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Familienname'), (1, 'Vorname')], db_default=0, verbose_name='Namensliste sortieren nach'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='touch',
            field=models.BooleanField(db_default=True, verbose_name='Touch erlaubt'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, db_default='', max_length=200, verbose_name='Username'),
        ),
    ]
