# Generated by Django 3.0.3 on 2020-03-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picker', '0014_credential_send_times_to_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('max_duration', models.IntegerField()),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picker.Credential')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
