# Generated by Django 4.0.3 on 2022-03-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0020_alter_credential_extractor_url'),
        ('stopwatch', '0002_alter_timeentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='congregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='picker.credential'),
        ),
    ]
