# Generated by Django 2.1.7 on 2019-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0002_auto_20190220_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='id',
        ),
        migrations.AlterField(
            model_name='credential',
            name='congregation',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
