# Generated by Django 2.1.7 on 2019-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0003_auto_20190220_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='autologin',
            field=models.CharField(default='', max_length=128),
        ),
    ]
