# Generated by Django 2.1.7 on 2019-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0004_credential_autologin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='autologin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
