# Generated by Django 4.0 on 2021-12-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show_in_locale',
            field=models.CharField(default=' ', max_length=10, verbose_name='Anzeigen für Sprache'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='locale',
            field=models.CharField(default=' ', max_length=10, verbose_name='Sprache der Nachricht'),
        ),
    ]
