# Generated by Django 3.0.7 on 2020-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Information'), (1, 'Wichtig'), (2, 'Dringend'), (3, 'Fehler')], default=0),
        ),
    ]
