# Generated by Django 3.0.7 on 2020-07-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200712_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='locale',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
