# Generated by Django 4.0 on 2021-12-16 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='max_duration',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig bis'),
        ),
    ]
