# Generated by Django 3.0.7 on 2020-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20200712_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Information'), (1, 'Wichtig'), (2, 'Dringend'), (3, 'Warnung')], default=0),
        ),
    ]
