# Generated by Django 5.0.6 on 2024-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Information'), (1, 'Wichtig'), (2, 'Dringend'), (3, 'Warnung')], db_default=0, verbose_name='Wichtigkeit'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='locale',
            field=models.CharField(db_default=' ', max_length=10, verbose_name='Sprache der Nachricht'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, db_default='', verbose_name='Nachricht'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='show_in_locale',
            field=models.CharField(db_default=' ', max_length=10, verbose_name='Anzeigen für Sprache'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(db_default='', max_length=255, verbose_name='Betreff'),
        ),
    ]
