# Generated by Django 3.0.8 on 2020-07-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20200713_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='max_duration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gültig bis'),
        ),
    ]
