# Generated by Django 2.2.6 on 2019-10-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('picker', '0006_auto_20191017_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='extractor_url',
            field=models.CharField(blank=True, default='http://localhost:5000/', max_length=200,
                                   verbose_name='Extractor URL'),
        ),
    ]
