# Generated by Django 2.2.7 on 2019-11-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0010_auto_20191126_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['display_name', 'congregation'], 'permissions': (('access_console', 'Zugriff auf Management Console'), ('access_stopwatch', 'Zugriff auf Stoppuhr'))},
        ),
    ]
