# Generated by Django 3.0.3 on 2020-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('message', models.TextField(blank=True, default='')),
                ('send_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['send_time'],
            },
        ),
    ]
