# Generated by Django 3.0.3 on 2020-02-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='congregation',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
