# Generated by Django 3.0.3 on 2020-02-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0013_auto_20200209_2208'),
        ('console', '0002_audit_congregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='congregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picker.Credential'),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.IntegerField()),
                ('start', models.DateTimeField(auto_now=True)),
                ('stop', models.DateTimeField()),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picker.Credential')),
            ],
            options={
                'ordering': ['talk', 'start'],
            },
        ),
    ]
