# Generated by Django 3.0.3 on 2020-02-18 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_auto_20200218_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='duration',
            new_name='max_duration',
        ),
    ]
