# Generated by Django 3.0.3 on 2020-02-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_auto_20200218_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='talk',
            field=models.CharField(max_length=255),
        ),
    ]
