# Generated by Django 3.0.3 on 2020-02-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_auto_20200220_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['start']},
        ),
    ]
