# Generated by Django 3.0.3 on 2020-02-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_auto_20200221_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
