# Generated by Django 3.0.3 on 2020-03-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_delete_audit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
