# Generated by Django 3.1.6 on 2021-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='Sprache'),
        ),
    ]
