# Generated by Django 3.1.6 on 2021-02-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_userpreferences_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='language',
            new_name='locale',
        ),
    ]
