# Generated by Django 3.2 on 2021-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_auto_20210209_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownClient',
            fields=[
                ('uri', models.TextField(primary_key=True, serialize=False, verbose_name='Client URI')),
                ('token', models.BinaryField(max_length=64, verbose_name='Token')),
            ],
        ),
    ]
