# Generated by Django 3.2 on 2021-04-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_knownclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownclient',
            name='alias',
            field=models.TextField(default='Client', verbose_name='Alias name'),
        ),
    ]
