# Generated by Django 3.2 on 2021-04-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0016_knownclient_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownclient',
            name='alias',
            field=models.TextField(default='Client', verbose_name='Alias Name'),
        ),
    ]
