# Generated by Django 3.2 on 2021-04-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0017_alter_knownclient_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownclient',
            name='uri',
            field=models.TextField(verbose_name='Client URI', primary_key=False),
        ),
        migrations.AddField(
            model_name='knownclient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='knownclient',
            unique_together={('id', 'uri')},
        ),
    ]
