# Generated by Django 3.2 on 2021-04-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_auto_20210422_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownclient',
            name='uri',
            field=models.TextField(unique=True, verbose_name='Client URI'),
        ),
        migrations.AlterUniqueTogether(
            name='knownclient',
            unique_together=set(),
        ),
    ]
