# Generated by Django 3.2 on 2021-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0019_auto_20210422_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownclient',
            name='cert_file',
            field=models.FileField(upload_to='certs'),
            preserve_default=False,
        ),
    ]
