# Generated by Django 3.2 on 2021-04-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0020_knownclient_cert_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownclient',
            name='cert_file',
            field=models.FileField(upload_to='certs', verbose_name='Zertifikatsdatei'),
        ),
    ]
