# Generated by Django 3.2 on 2021-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0021_alter_knownclient_cert_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownclient',
            name='uri',
            field=models.URLField(unique=True, verbose_name='Client URI'),
        ),
    ]
