# Generated by Django 3.2.1 on 2021-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0022_alter_knownclient_uri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knownclient',
            options={'ordering': ['alias', 'uri'], 'verbose_name': 'Bekannter Client', 'verbose_name_plural': 'Bekannte Clients'},
        ),
        migrations.AlterField(
            model_name='knownclient',
            name='uri',
            field=models.URLField(unique=True, verbose_name='Client URL'),
        ),
    ]
