# Generated by Django 3.2.3 on 2021-05-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0023_auto_20210505_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knownclient',
            options={'ordering': ['alias', 'uri'], 'permissions': (('control_client', 'Client steuern'),), 'verbose_name': 'Bekannter Client', 'verbose_name_plural': 'Bekannte Clients'},
        ),
    ]
