# Generated by Django 5.0.4 on 2024-04-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0027_remove_userpreferences_dark_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='design',
            new_name='scheme',
        ),
    ]
