name: Django CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build Release Info
        id: build_release_info
        run: |
          echo ::set-output name=version::${TAG_REF_NAME##*/v}
        env:
          TAG_REF_NAME: ${{ github.ref }}
      - name: Build project
        run: |
          mkdir dist
          cd .. && zip -r StagyBee/dist/StagyBee-${{steps.build_release_info.outputs.version}}.zip StagyBee -x "StagyBee/.git/*" "StagyBee/.github/*" "StagyBee/.idea/*" "StagyBee/.gitignore" "StagyBee/dist/*" && cd StagyBee
          tar --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='.idea' --exclude='dist' -cvf dist/StagyBee-${{steps.build_release_info.outputs.version}}.tar ../StagyBee
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: StagyBee-${{steps.build_release_info.outputs.version}}
          path: dist