name: Django Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.2"
          python-version-file: "app/pyproject.toml"
      - name: Run Tests
        run: |
          python app/manage.py test ./app
          pytest app/stage/tests/test_consumers.py app/console/tests/test_consumers.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
        env:
          DEBUG: on
          DJANGO_SETTINGS_MODULE: StagyBee.settings
          PYTHONUNBUFFERED: 1
